### PR TITLE
Update xml2js dependency

### PR DESCRIPTION
**Pull request by sebdec**
vulnerability details: https://github.com/advisories/GHSA-776f-qx25-q3cc
fix this: https://github.com/fiznool/body-parser-xml/issues/172

### CODE REVIEW

**Comment by fiznool** [comment]
Thanks for the contribution! I will cut a new release when I'm back at my desk later today.

**Comment by mzubairsaleem** [comment]
Thanks, Looking forward to it.

**Comment by mzubairsaleem** [comment]
> Thanks for the contribution! I will cut a new release when I'm back at my desk later today.

@fiznool Can you see to this Release?

**Comment by fiznool** [comment]
Published as 2.0.5

**Pull request merged**
